### ISSUE TITLE
Sorting of database search results does not apply immediately

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#105]
After entering a search query in the search bar with a selected sorting method, the search results do not sort automatically. The sorting would work once you click on a different sorting method then the intended sorting method again.

[Recording 2024-04-13 222404.zip](https://github.com/SE-Nex-Tech/Nex.Tech/files/14967632/Recording.2024-04-13.222404.zip)

**Comment by KyleZrey** [comment]
fixed either unintentionally or did not get tagged in a PR

**Comment by KyleZrey** [comment]
Not yet fixed, should refresh table with the search and sort selection.
