### ISSUE TITLE
Invalid values in Sign up page are accepted by the system

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#107]
The first name and last name text fields must only accept alphabetical inputs.

Employee/Student number should notify the user if the number of digits is less or more than 10.

Password placeholder indicates to generate a password with at least 6 characters, but it can accept passwords that are less than the minimum.

![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/864e17bb-6e0d-4d41-9240-24be4e459b06)

![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/b6d60eaa-f63c-4361-b621-c69f384f91af)

![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/7a68822c-c83c-4971-b31f-6c82f6b31692)

**Comment by KyleZrey** [comment]
@EdjinJerney @1123Alessandro, I thought this was fixed (#79) already? still existing in main

<img width="1246" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/d8eba3ff-3780-4439-b801-6478c305b01e">
