### ISSUE TITLE
Dbpage Boardgames Sorting & Archiving

### ISSUE THREAD

**Issue by edjinjerney** [SE-Nex-Tech/Nex.Tech#118]
The Sort feature does not work for the Boardgames table in the dbpage
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/214db8c5-0641-49e6-9002-554a655f82ca)

Editing existing records in the dbpage places them to the last page of the table
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/8ab8a734-17b2-4317-b01b-50a811228e02)
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/b5baa4b0-13dc-4212-b775-c61e850e8dbb)
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/65845414-d0c1-43f5-b7d5-d9d85c1f6a48)

Archiving records in the table sets the archive property to true, but it is still visible in the table
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/1153ff31-ead6-4734-8074-7fe4c7be4728)
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/98964fc8-297f-4871-b0ae-b91f3080183d)

**Comment by KyleZrey** [comment]
for the archiving issue, add the same change from /books to /games
<img width="580" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/e8f204bb-e61a-42af-8085-dcdb9d318021">
