### ISSUE TITLE
Borrowed book has not changed the status in the system

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#34]
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/f6072aa2-1831-4283-bc53-a414f3d6036e)

In the general user mode, Digital Dynamics was borrowed by a Faculty member.

When another user attempts to borrow the same book, the status show that it is still "Available."

<img width="931" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/41be46f6-8c48-4606-a909-eba43134c3b6">

The book can be borrowed normally.

<img width="931" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/de66a9c9-93f8-45c7-9597-f7ec2e5d01e7">

**Comment by 1123Alessandro** [comment]
feature WIP
