### ISSUE TITLE
Borrowed book has not been updated in the reports page

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#35]
<img width="931" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/083afb9f-20f2-4751-9fde-2b587a59c206">

The Digital Dynamics book was borrowed and scanned in the QR scanner, but it has not been updated in the Request Summary.

**Comment by 1123Alessandro** [comment]
feature WIP
