### ISSUE TITLE
Link to redirect the user to UST Miguel de Benavides Library Website

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#43]
<img width="932" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/9d53ccd0-40bf-4be9-afbe-9583246af483">

The button to redirect the user to the UST Miguel de Benavides Library website. Also, add "de" in between "Miguel" and "Benavides" in the button label.

**Comment by 1123Alessandro** [comment]
already fixed by PR #40. Only report bugs to **completed features**
