### ISSUE TITLE
Add a restriction for invalid date range

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#44]
<img width="930" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/af6c6ec1-7e13-4766-a858-6066214df316">

March 16, 2024 and March 8, 2024 are future dates as of today (March 6, 2024).

Disable the selection of invalid dates in the calendar.

<img width="539" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/d51ecacb-3c51-4935-ab5d-d821aaf87c13">

Also restrict the input for _future date_ to _past date_ for easy reading of records.

**Comment by 1123Alessandro** [comment]
fix already in PR #42
