### ISSUE TITLE
Database sorting not working

### ISSUE THREAD

**Issue by KyleZrey** [SE-Nex-Tech/Nex.Tech#46]
Login > Database > Sort by: Any choice does not work

<img width="1470" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/c8cdd82e-37c8-4ad4-88d6-ffc0e101880a">

_No sorting happens whichever sorting preference the user chooses._

**Comment by KyleZrey** [comment]
still not working on all browsers. It works fine on some.

<img width="1470" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/04c89ae9-dd18-4c6a-88b5-7592c6c1405f">

**Comment by 1123Alessandro** [comment]
Post this as a separate issue with complete instructions for reproducibility
