### ISSUE TITLE
Sorting feature in the Admin Database

### ISSUE THREAD

**Issue by alpacaShiro** [SE-Nex-Tech/Nex.Tech#67]
When utilizing the search feature of the database, the results will be sorted by ID number in ascending order. The database remains sorted in ascending ID numbers when sorting the ID numbers in descending order.

![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/100348938/2f6a441f-eeea-4018-a042-dcfb59e1a44d)

The same goes for sorting the Item Title and Item Author in ascending and descending order.

**Comment by 1123Alessandro** [comment]
Try different browsers, record a video of the bug if it persists
