### ISSUE TITLE
bug: marked values in the database page 

### ISSUE THREAD

**Issue by KyleZrey** [SE-Nex-Tech/Nex.Tech#76]
Select any value visible from the front of the table:
<img width="1109" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/34781560-44e9-4fdf-911f-76fad36ae1f7">

Then, try to search for other books unrelated to the marked value:
<img width="1111" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/47fdd6f0-4301-495c-a745-bec6c6232ec2">

Note that only selected book ID#4, but when searching for others, it reflects that I have selected book ID#7, which I didn't. 

However, when Archive button is clicked, it reflects the right selection of book/s.
<img width="1046" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/401bcc98-5b24-45a6-81d0-5f63be60294d">

Retain the marked status on the specific book/s clicked, not on the marked position of the table.

more proof:
<img width="1117" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/50375786-2f46-42da-9bff-e26f0b33c619">
Note: Book ID # 3-7 is selected

After searching, it displays other books as marked when they are in the same position in the displayed table from the previous selection.
<img width="1064" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/eeb7e34d-6fc5-4b46-8b5d-941b1d1cde57">

This will be confusing when the admin searches and marks multiple instances, fix immediately.

**Comment by 1123Alessandro** [comment]
This is a front-end issue, pagination to be exact. replace label and tag appropriate developers

**Comment by KyleZrey** [comment]
> This is a front-end issue, pagination to be exact. replace label and tag appropriate developers

fixed labels, paging @carlmitzchel

**Comment by KyleZrey** [comment]
fixed either unintentionally or did not get tagged in a PR
