### ISSUE TITLE
Admin Signup Page: no input restrictions (empty values, etc.)

### ISSUE THREAD

**Issue by KyleZrey** [SE-Nex-Tech/Nex.Tech#79]
Signup without filling up the personal information form:
<img width="566" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/f0f0bfa4-5450-43d2-b3b3-1de080572fb7">

<img width="1050" alt="image" src="https://github.com/SE-Nex-Tech/Nex.Tech/assets/119041472/644a5c67-ffae-4e44-b77a-70caa139cfb1">

**Comment by 1123Alessandro** [comment]
@EdjinJerney can you put input checking for this?

**Comment by carlmitzchel** [comment]
@EdjinJerney created a <a href="https://github.com/SE-Nex-Tech/Nex.Tech/pull/83">branch</a>  that prevents the user from signing up when an input field is empty. Still requires input checking

**Comment by 1123Alessandro** [comment]
@carlmitzchel don't forget to tag the issue to the pr
